### ISSUE TITLE
Footprints may not be correct

### ISSUE THREAD

**Issue by manthey** [ResonantGeoData/ResonantGeoData#103]
A spatial reference is not completely captured by the srid, resulting in bad footprint polygons.

I have a sample file where the coordinate system is wkt 

```
PROJCS["Albers Conical Equal Area",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.2572221010042,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4269"]],PROJECTION["Albers_Conic_Equal_Area"],PARAMETER["standard_parallel_1",29.5],PARAMETER["standard_parallel_2",45.5],PARAMETER["latitude_of_center",23],PARAMETER["longitude_of_center",-96],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]
``` 

When we create the raster footprint, we have a `SpatialReference` with this wkt and we create a `Polygon` with `srid=spatial_ref.srid`, but the `srid` is just `4269`, which is not in the same units as the actual spatial reference.  Specifically, we are trying to do: 

```
Polygon([[1319547.040429464, 2658548.125730889], [2005547.040429464, 2658548.125730889], [2005547.040429464, 2148548.125730889], [1319547.040429464, 2148548.125730889], [1319547.040429464, 2658548.125730889]], srid=4269)
```

but this doesn't work.

A sample file:
[landcover_sample_2000.zip](https://github.com/ResonantGeoData/ResonantGeoData/files/4927886/landcover_sample_2000.zip)

I think we need to convert our boundary polygon before creating a Django GEOSGeometry polygon.  Another option might be to register each coordinate system we use via `django.contrib.gis.utils.srs.add_srs_entry`, but I haven't checked if that would work.

**Comment by banesullivan** [comment]
> I think we need to convert our boundary polygon before creating a Django GEOSGeometry polygon.

I think that would be the safest bet. I'll see if I can find a workaround to do this conversion.

The other thing that bothers me is that this footprint polygon does not appear within the default admin view for these Polygon fields (when we turn off read-only for the field, an interactive map appears that should show the polygon on the map).

**Comment by manthey** [comment]
I think I have a solution for the transform.  I don't know why it doesn't appear on the map (unless it is related).

**Comment by banesullivan** [comment]
My gut tells me it's related but I'm not sure. If you have a solution, go for it! thanks!

**Comment by manthey** [comment]
There are two actual issues.  One is caused by using a SRID when we need to use a more complex WKT.  The other is is Django issue.

It turns out the Django < 3.1 doesn't actually support GDAL >= 3.0.  They *work* with it, but don't actually work with it properly.  Specifically, as of Proj4 6 and GDAL 3, both Proj4 and GDAL now honor axis order of CRS definitions.  This means some CRS are easting, northing or longitude, latitude and other CRS are northing, easting or latitude, longitude.  See https://code.djangoproject.com/ticket/30645 for some more details.

The solution is to (a) update to Django >= 3.1 (though this is still in beta), and (b) do something like
```
                src_spatial_ref = SpatialReference(src.crs.to_wkt())
                db_spatial_ref = SpatialReference(DB_SRID)
                logger.info(f'Raster outline SRID: {src_spatial_ref.srid}')
                outline = Polygon(coords)
                transform = CoordTransform(src_spatial_ref, db_spatial_ref)
                outline.transform(transform)
```
Although it is possible to work around some of the issues with axis order without upgrading Django, results are inconsistent.  It would involve checking the axis order (which can be done via pyproj) and reversing coordinates when applicable.  However, in Django 3.0.x, the database expects coordinates in longitude, latitude but some plugins (such as the map in admin view) expect latitude, longitude.

Functionally, Django 3.0 does not work with GDAL 3, and there aren't builds for GDAL 2.x for Python 3.8.  I think upgrading to Django 3.1b1 is the short term solution.  Django 3.1 isn't officially going to be released until August 3 (https://code.djangoproject.com/wiki/Version3.1Roadmap).  The other options are (a) to build GDAL 2.x for Python 3.8, (b) add hacky coordinate transforms that **will** be wrong with newer versions of Django, or (c) downgrade to an older Python so we can use existing builds of GDAL 2.x.

**Comment by banesullivan** [comment]
> (b) add hacky coordinate transforms that will be wrong with newer versions of Django

Hm, so would the `transform_geometry` method I have in #105 not work in newer versions of Django?
