### ISSUE TITLE
Django admin geometry previewer not showing base map

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#130]
the default geometry viewer included with GeoDjango is not showing the OpenStreeMap base map layer on the deployed website.

| Locally | Deployed |
| --- | --- |
|  <img width="824" alt="Screen Shot 2020-08-11 at 10 34 09 AM" src="https://user-images.githubusercontent.com/22067021/89923710-3b193b80-dbbe-11ea-9ede-9e4423a51116.png"> | <img width="821" alt="Screen Shot 2020-08-11 at 10 34 20 AM" src="https://user-images.githubusercontent.com/22067021/89923733-42d8e000-dbbe-11ea-820a-e41609c0d6e9.png">  |

**Comment by manthey** [comment]
Strange, all seven raster entries show the basemap for me.

**Comment by banesullivan** [comment]
Huh. I double-checked this. It works in Chrome but not Safari. 

Solution: use Chrome!

**Comment by banesullivan** [comment]
Likely an upstream issue not worth our time

**Comment by manthey** [comment]
Good to know  I only checked on Firefox and Chrome.
