### ISSUE TITLE
FMV Support

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#142]
This issue is a place to track progress and details for implementing support for Full Motion Video (FMV)

FYI: [this is helpful](https://www.remotegeo.com/demystifying-misb-fmv-full-motion-video/) for those unfamiliar with FMV.

### Available Data

The VIRAT AP Hill data is the closest thing that does not come with any usage restrictions. It is publicly released and has KLV metadata. This dataset is hosted by Kitware [here](https://data.kitware.com/#collection/56f56db28d777f753209ba9f/folder/56f57fa48d777f753209c713). 

### Spatial Reference / Metadata

- The KLV metadata is encoded in a video file (e.g. MP4) and has geospatial metadata included in that file in the KLV format.
- Most other data sets either have no metadata, or the metadata is stored in a separate file (e.g. CSV), or the "video" is actually a sequence of JPEGs and the metadata is stored as EXIF in the JPEG headers.
- We should focus on KLV metadata as that's what our customers/users are interested in.
- KLV is in a separate stream within the video file, much like audio is.

We can use Kwiver to extract this FLV metadata with the `kwiver dump-klv` command-line tool.  Source [here](https://github.com/Kitware/kwiver/blob/master/arrows/core/applets/dump_klv.cxx). To use it, download the Docker image published for Kwiver [here](https://hub.docker.com/r/kitware/kwiver/tags) and run the tool with the video file. For example:

```
HOST_MNT=$PWD/
CONT_MNT=/home/
CONT_PWD=/home/

docker run --rm -v $HOST_MNT:$CONT_MNT:delegated -w $CONT_PWD kitware/kwiver:release /kwiver/build/bin/kwiver dump-klv VIRAT/09152008flight2tape1_1.mpg
```

where `09152008flight2tape1_1.mpg` saved in the `VIRAT` folder and is the [first video](https://data.kitware.com/#item/56f57fa48d777f753209c714) in the dataset.

Note that we are currently having trouble with that Docker image as Kwiver might not be properly configured with FFmpeg. See https://github.com/Kitware/kwiver/pull/1070 for details and a potential fix.

At the moment, I am roadblocked from continuing this until the Docker image is fixed and we can use it to extract the FLV metadata.

### Next Steps

- [x] Use an updated Kwiver Docker image to extract FLV metadata
- [x] Create a parser for the FLV metadata to extract the spatial reference of the FMV datasets that we could use for cataloging. **The two features of interest:**
  - [x] flight path
  - [x] footprint
- [x] Set up an ETL routine that will except FMV datasets and automatically do the cataloging
  - [x] Extracts FLV metadata with Kwiver and saves that in the Database
  - [x] parses features of interest from FLV data and saves those

**Comment by banesullivan** [comment]
I built a Docker image for Kwiver from https://github.com/Kitware/kwiver/pull/1070 and pushed it to Docker hub for use [here](https://hub.docker.com/repository/docker/banesullivan/kwiver/). The `kwiver dump-klv` command-line tool is working and I can fetch the KLV metadata. 

Now I just need to write a parser for this to extract the flight path and footprint

**Comment by mleotta** [comment]
We can also consider improving the output of dump-klv to make it easier to parse.  We actually have a task on another project to do just that, probably by writing the data to a CSV file.  Let me know if you have any input on how to improve the output of dump-klv to make it easier to use.

**Comment by banesullivan** [comment]
I'll let you know, but I'm currently able to iterate over the dumped string with some regular expressions to extract the sensor location and frame corner points quite easily so it all works fine for me as is
