### ISSUE TITLE
FMV Detail View: show footprint of frame while previewing video

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#146]
Task: show a live footprint on a map while playing the video.

#145 adds a detailed view page for FMV datasets that shows a preview of the video and the entire video's ground footprint. We need to update this page to synchronize the GoeJS viewer to show the current polygon for the frame shown in the video preview.

Unfortunately, the number of footprint polygons that we store is not guaranteed to have a 1-to-1 mapping back to the video frames (some frames could be lacking a footprint... in that case, we will use the last available footprint).

Because of that lack of 1-to-1 correspondence, we need a way to track which polygons correspond to which frames. At present, this information is only known during the ETL routine and the mapping is lost after we save the `FMVEntry`. To track this, we could store an array of the frame indexes for each of the Polygons that were saved to the model as a binary blob. Then we'd have an N-length array of those indices and a `MultiPolygon` of N polygons that we could pass to the view. One thing to note is that this could easily approach 10K polygons. From there we could have a custom video viewer coupled to the GeoJS viewer that will keep track of the current video frame and use that to update the polygon rendered by the GeoJS viewer.

@manthey, I'm not sure how to create this custom viewer that will track the frame index, any suggestions?

**Comment by manthey** [comment]
There are two approaches, depending on whether we ever want to display multiple frames' polygons or not.  You can create a feature with all the polygons for all the frames frame.  The visibility (via the stroke and fill) of each polygon can be toggled for the appropriate frame.  This approach worked for another project with ~11k frames.  There we had an option to show all the polygons, which, while it made an interesting spirograph-like pattern, wasn't particularly useful.  Alternately, you can have a feature where the data is the polygon for the current frame and the data is changed when the frame changes.

If , for instance, we had a GeoJSON object with all of the polygons for all of the frames, and each polygon had a property with a key we designate for the frame, then we could specify functions for the geojs polygon `stroke` and `fill` options that checks the attribute frame value against a variable that has the current frame number.  For instance, after loading the geojson via a reader:
```
reader(geojson, (features) => {
  features[0].style({
    stroke: (d, i, polygon) => polygon.properties.frame == videoplayerState.currentFrame,
    fill: (d, i, polygon) => polygon.properties.frame == videoplayerState.currentFrame,
  });
})
```
(note, I just wrote this without testing, so I may have it wrong).
