### ISSUE TITLE
database migration to initialize for demos

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#160]
We should create a migration to populate the database with entries to be able to quickly spin up demos and have some sample data for folks to see on the deployed website.

It'd be great to aggregate example data (likely just what is included in the datastore for the `geodata` tests coming from data.kitware.com) and include those. We could also do the same for the `core` app.

I'm pretty sure this would be implemented in a manually created migration, is that the best way to go about it? 

Would everyone be on board with this, or should we have it as an optional feature maybe for the deployed site only?

**Comment by banesullivan** [comment]
It would be great if we could import a good chunk of Landsat 8 data from https://registry.opendata.aws/landsat-8/

This seems like an ideal example as we could point to the original data on S3 (and I believe it is all in COG format)

> Landsat 8 data is available for anyone to use via Amazon S3. All Landsat 8 scenes are available from the start of imagery capture. All new Landsat 8 scenes are made available each day, often within hours of production.
> ...
> Landsat data is in AWS S3 bucket named landsat-pds and is organzied by path, row, and scene.

**Comment by banesullivan** [comment]
@mcovalt asked me to provide a list of public datasets that we should use for testing. I thought this would be the appropriate place to list those so that, down the road, we can use these data as the default:

- FMV data: [Virat v2 Aerial on DKC](https://data.kitware.com/#collection/56f56db28d777f753209ba9f/folder/56f57fa48d777f753209c713)
- East River Watershed: See [this folder on DKC](https://data.kitware.com/#user/5edea5859014a6d84eabf0f0/folder/5f9c31fe50a41e3d1920f08f)
    - Geometry: see the `Streams.zip` and `Watershed.zip` archives there
    - Rasters: There is one GeoTIFF in this folder and I will add others there later (I will get a number of different rasters off Earth Explorer to have around that project site)
- KWCOCO: There are some [very simple examples on DKC](https://data.kitware.com/#user/5edea5859014a6d84eabf0f0/folder/5f9c31a850a41e3d1920effb) but I have many other, larger databases that are bot public that we can use locally.

**Comment by manthey** [comment]
There are seven tiny raster files we are using for [testing on DKC](https://data.kitware.com/#collection/5ed11a7f9014a6d84e93c7d6/folder/5f1f37409014a6d84e4236f5).  I could also upload higher resolution versions of most of those, if that is useful.

**Comment by banesullivan** [comment]
Addition data we can use: https://data.kitware.com/#user/5450e5e88d777f0707be5fdd/folder/5bfff53f8d777f2179c70e82
