### ISSUE TITLE
Add thumbnail to ImageEntry on ETL

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#170]
1. Use rasterio/GDAL to save a small thumbnail of all imagery to the `ImageEntry` model during the ETL routine 

2. provide a way to pull that image and overlay it in the GeoJS front end

@manthey, should I add a new argument to the endpoints such as `&thumbnail=true` with a default value `false` to pull the thumbnail as a part of the query results when they return rasters/other imagery?

**Comment by manthey** [comment]
Perhaps we should have a ThumbnailImage model which would inherit from ImageEntry but not be included in default endpoint results.  I'm not sure when we'd want to a search to return the thumbnail AND the source of the thumbnail, so I'm not sure about adding an argument to the endpoints (when we'd want the value of `&thumbnail` to be `true`?).  I think, in general, we'd want to know an ImageEntry has an associated thumbnail and perhaps the size of the thumbnail.

For reference, in Girder, we store thumbnails as associated files which get listed differently than files associated with an item.  In large_image, you can ask for thumbnails of any size, specifying the maximum width and/or height.

**Comment by banesullivan** [comment]
Hm. What if I implement a new `Thumbnail` model that will have a related `ImageEntry` field and a single file field for storing a single thumbnail (I'm hesitant to add inheritance for this because of how the `ImageEntry` model is used by `RasterEntry`). By default, this file field will have a single low-resolution thumbnail of the `ImageEntry` produced during the ETL routine. From there we can include an endpoint for fetching thumbnails from that `Thumbnail` model.

For now, the endpoint will only serve that one thumbnail that is saved during the ETL routine (and in the file field), but once we have a Django hookup for `large_image` we can add that to this model to be able to dynamically take requests for differing resolution thumbnails.

> For reference, in Girder, we store thumbnails as associated files which get listed differently than files associated with an item. In large_image, you can ask for thumbnails of any size, specifying the maximum width and/or height.

Would I then need a way to associate multiple files with this `Thumbnail` model so that if a thumbnail is produced at some specified resolution, we track that? Or would we wait and let `large_image` do that caching?

**Comment by manthey** [comment]
> Hm. What if I implement a new `Thumbnail` model that will have a related `ImageEntry` field and a single file field for storing a single thumbnail (I'm hesitant to add inheritance for this because of how the `ImageEntry` model is used by `RasterEntry`). By default, this file field will have a single low-resolution thumbnail of the `ImageEntry` produced during the ETL routine. From there we can include an endpoint for fetching thumbnails from that `Thumbnail` model.
> 
> For now, the endpoint will only serve that one thumbnail that is saved during the ETL routine (and in the file field), but once we have a Django hookup for `large_image` we can add that to this model to be able to dynamically take requests for differing resolution thumbnails.

Sounds good.
 
> > For reference, in Girder, we store thumbnails as associated files which get listed differently than files associated with an item. In large_image, you can ask for thumbnails of any size, specifying the maximum width and/or height.
> 
> Would I then need a way to associate multiple files with this `Thumbnail` model so that if a thumbnail is produced at some specified resolution, we track that? Or would we wait and let `large_image` do that caching?

I'd wait until we have large_image to do this.  large_image caches multiple sizes of thumbnails (there is a setting on how many can be cached per parent item).  It generates thumbnails on demand and also has a server job that can generate thumbnails for all large images from a list of sizes.  To complicate matters further, some image files have the main image and some associated images (in microscopy these are usually macro and label images -- a low resolution version of the whole slide and a version of just the label), and these are fetched and cached in a similar manner to thumbnails (you can request them at different sizes, for instance).

**Comment by banesullivan** [comment]
> I'd wait until we have large_image to do this.

Sounds good to me then

> to complicate matters further...

I may wait until that use case presents itself to the geodata app before incorporating it into current design decisions.
