### ISSUE TITLE
COG ImageEntry conversion endpoint

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#198]
We need to add an endpoint to convert any ImageEntry to COG format

**Comment by manthey** [comment]
I've found the following command line works well:
```
gdal_translate <inputPath> <outputPath.geotiff> -of COG -co BIGTIFF=YES -co BLOCKSIZE=<tileSize> -co COMPRESS=<JPEG|DEFLATE|LZW|ZSTD> -co QUALITY=<jpeg quality where 100 is high quality> -co PREDICTOR=YES
```
Ideally, we'd use JPEG compression for lossless source files and probably LZW for others.  I'd use a jpeg quality of at least 90 to avoid introducing artifacts.  If we use ZSTD compression, we can also specify a compression `-co LEVEL=<level>`.

**Comment by banesullivan** [comment]
Awesome, thanks @manthey!

-------

To implement this, I am thinking of the following approach:

- add a new POST endpoint that will accept an `ImageEntry` ID (primary key) and trigger a task
    - `api/geodata/imagery/image_entry/convert/<str:format>/<int:pk>` (where COG will be the only supported format for now)
- This endpoint will run the ^above command and create a new `ConvertedImageFile` adding that file to that model and associating it's `source_image` field to that `ImageEntry`.
- add a new string field to the `ConvertedImageFile` to keep track of the format and set that to COG (I imagine GDAL has a set of keys we can use for this)
- Since this conversion will be asynchronous, the endpoint will return a reference to the newly created `ConvertedImageFile` and we will need another endpoint for checking that entry (initially setting the file as null)
- Add a new endpoint to access `ConvertedImageFile`
    - GET endpoints for: `status`, `format`, and the file itself: `api/geodata/imagery/converted_image_files/<int:pk>/<thing to fetch>`. e.g. `api/geodata/imagery/converted_image_files/15/file/`
