### ISSUE TITLE
Add endpoint to serve ROIs of images as raw arrays

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#201]
(for the ndsampler use case)

We need to add endpoints to access arbitrary ROIs of images and serve the pixels of those ROIs as raw arrays.

This will likely require #198 under the hood

Will we want to use `large_image` for this?

-----

I imagine the endpoints being something like `GET:api/geodata/imagery/image_entry/roi/<ROI query parameters>` which will send back a serialized array of that ROI. The ROI query parameters will be a tricky part to get right for versatility. Immediately, I can think of a few common ways folks may want to use this:

- simple pixel coordinate bounding box: `umin,umax,vmin,vmax`
- geospatial bounding box: `xmin,xmax,ymin,ymax` (world coordinates)
- GeoJSON polygon we serve the region of the image surrounding that polygon

Perhaps each of those should be seperate endpoints?

- `GET:api/geodata/imagery/image_entry/roi?geojson=<geojson str>`
- `GET:api/geodata/imagery/image_entry/roi/pixel_box?umin=50&umax=150&vmin=90&vmax=200`
- `GET:api/geodata/imagery/image_entry/roi/geo_box?minimum_longitude=-107.35&maximum_longitude=-104.63&minimum_latitude=39.48&maximum_latitude=41.51`

**Comment by banesullivan** [comment]
@manthey, thoughts?

Also, how should I approach serving the raw data? Should we use this as a motivator to integrate `large_image`?

**Comment by manthey** [comment]
@banesullivan Do we know what format we want to server the raw arrays in?  large_image serves image tiles; currently these can be in PNG, JPEG, or TIFF.  The PNG and TIFF are lossless, but I think they are always reduced to 8 bits-per-sample.  One virtue of large_image is that is already handles reprojections.  If needed it would be straightforward to add an additional output format (protobuf or something similar, for instance, or TIFFs with a different bits-per-sample).

**Comment by Erotemic** [comment]
> each of those should be separate endpoints

Yes

>  and serve the pixels of those ROIs as raw arrays.

Ultimately, I'll want to get a numpy array of pixel values, but the if we are talking about serialization for network transport, I don't think raw arrays is the right choice. I think its perfectly reasonable for RGD to send some encoded subimage region and then assume that the user is able to do something like calling `cv2.imdecode` or some GDAL equivalent on the result.
