### ISSUE TITLE
Remove core app

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#216]
Since we have the @ResonantGeoData org account and we are not using the `core` app at all anymore, we should pull it out into a separate repo under this org.

Having the `core` app's code/config still in here adds maintenance burden, e.g. #210

**Comment by manthey** [comment]
To browse the code before the core app is removed, see https://github.com/ResonantGeoData/ResonantGeoData/tree/cb6ec0e36abd697c7b84a0533e3526854049b65b
