### ISSUE TITLE
_convert_to_cog function doesn't generate COG

### ISSUE THREAD

**Issue by manthey** [ResonantGeoData/ResonantGeoData#222]
The current _convert_to_cog function (https://github.com/ResonantGeoData/ResonantGeoData/blob/master/rgd/geodata/models/imagery/subsample.py#L32-L51) doesn't output a COG; it just outputs a tiled tiff file.  GDAL has two separate format writers; one for regular TIFF and one for COG.  Without the '-of COG' option, the regular tiff writer is invoked.  The options available to the two writers differ as well: for COG you can specify a predictor with a string value, for regular tiff you must specify a numeric predictor value.

Using lzw compression, I'd recommend the following options: `['-co', 'COMPRESS=LZW', '-co', 'PREDICTOR=YES', '-of', 'COG']`.  The default block (tile) size in the COG writer is 512 pixels; some tile servers or consumers seem to prefer 256; if so, add `-co BLOCKSIZE=256`.

You can use tiffdump to see that COG files have multiple directories at different resolutions while non-COG files have a single directory.

**Comment by banesullivan** [comment]
Ah, thanks for catching this, @manthey! I had been using a utility in GDAL to "verify" that a TIFF is in COG format and blindly trusted that: https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/samples/validate_cloud_optimized_geotiff.py

I will update `_convert_to_cog` with these options and use tiffdump to validate things locally.
