### ISSUE TITLE
Remove the "download_file" endpoint

### ISSUE THREAD

**Issue by brianhelba** [ResonantGeoData/ResonantGeoData#253]
The `download_file` endpoint:
* https://github.com/ResonantGeoData/ResonantGeoData/blob/18134ae087e83637e02182eea4940dfe02ab7dfa/rgd/geodata/api/download.py#L19
* https://github.com/ResonantGeoData/ResonantGeoData/blob/657ca335fe81b906441f9ba326df099fc05b1e32/rgd/core/views.py#L131

will not work on a production deployment with large files or users with slow connections.

All HTTP requests served by the API server must terminate within 30 seconds: https://devcenter.heroku.com/articles/request-timeout

Additionally, tying up a request thread on the API server for long-running (anything greater than 3-5 seconds max) requests will cause significant scalability problems.

Downloading files directly from the storage backend should already be fully supported in all development and production environments.

**Comment by banesullivan** [comment]
I can remove these easily. We currently have endpoints that use `HttpResponseRedirect` to forward to the filedield's URL

**Comment by banesullivan** [comment]
Done in #251
