### ISSUE TITLE
Large image application

### ISSUE THREAD

**Issue by mcovalt** [ResonantGeoData/ResonantGeoData#260]
A small part of https://github.com/girder/large_image/issues/524 needs to be implemented for this Django project. The parts needed are:

- [ ] endpoint or method to make / unmake a Django file field into a large_image item
- [ ] endpoints for metadata (/tiles)
- [ ] endpoints for serving tiles (/tiles/zxy)

**Comment by banesullivan** [comment]
> endpoint or method to make / unmake a Django file field into a large_image item

For this, we need to support `ChecksumFile` generally: both when `FileField`/`S3FileField` or a remote URL is specified. Perhaps the simplest approach would be to have `large_image` accept a resource URL and produce an item from that (`FileField` has an associated URL we can yield) -- this would make the interface consistent regardless of where the file is coming from and help us avoid `field_file_to_local_path`
