### ISSUE TITLE
Point to an S3 bucket and auto-ingest all data

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#302]
Can we figure how to auto ingest data that match criteria from an existing bucket?

e.g. ingest all GeoTiffs given the bucket location

**Comment by banesullivan** [comment]
Perhaps we could implement this as a `manage.py` command (much like the demo data commands) where we pass the following parameters:

- bucket name/location
- regex - the filename pattern to look for
- datatype - whether we want to ingest the files as just `ImageEntry`s, `RasterEntry`s, `FMVEntry`s, or `GeometryEntry`s (perhaps we could automatically decide this based on file extension and presence of spatial reference in image files)
- [optional] count - the number of files/resources to import
- [optional] credentials - authenticating the boto3 client for accessing non-open access resource

We will also want to have a check to make sure an existing `ChecksumFile` doesn't already point to this resource to avoid duplicate entries

**Comment by zachmullen** [comment]
I'm assuming the goal is to copy the data from the S3 bucket into RGD's storage?

**Comment by banesullivan** [comment]
Not copy, but index. RGD's `ChecksumFile` model has a `URL` mode:

https://github.com/ResonantGeoData/ResonantGeoData/blob/8e1afd784be7bb4cdf45bbab56b0497a9b1e21ee/rgd/geodata/models/common.py#L105-L107

https://github.com/ResonantGeoData/ResonantGeoData/blob/8e1afd784be7bb4cdf45bbab56b0497a9b1e21ee/rgd/geodata/models/common.py#L133-L135

We want to create `ChecksumFile`s with the url to the resources in the S3 bucket to avoid copying the data. The intent here is for RGD to be a catalog of the existing, external data.

The ETL routines only parse the headers of image/raster files, so it would be highly inefficient to copy the files over when we can just FUSE mount to the remote file, grab the meta info from the header, then move on.

-----

For a first pass, having publicly accessible URLs is good enough. later, we will need a way to provide user credentials depending on the user/collection that the `ChecksumFile` belongs to.
