### ISSUE TITLE
Add an example on how to ingest data via STAC catalog 

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/ResonantGeoData#377]
@mcovalt I believe I heard that we are very close. Can we put together an example on how it can be done. We need this asap for our University customers.

**Comment by banesullivan** [comment]
This is pretty much done in #461. It's rather simply really:

simply load each raster/STAC Item as a dict in Python and pass that to the RGD Python client:

```py
stac_item = ...  # load JSON as dict

client.create_raster_stac(stac_item)
```

This requires that each asset in the STAC item have the appropriate `data` tag and the files be pre-uploaded to S3.
