### ISSUE TITLE
GeoAdmin widget incorrectly rendering geometry

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#391]
The `OpenLayersWidget` we are using in the admin view of the geo Django models is incorrectly rendering geometry. I suspect this is a simple coordinate issue where we need to transform the geometry before passing it to the model admin widget:

https://user-images.githubusercontent.com/22067021/117475485-5761c300-af19-11eb-97b5-7cd8e29bf14c.mov

**Comment by banesullivan** [comment]
This is only an issue when the widget is a `admin.StackedInline`

**Comment by banesullivan** [comment]
I believe this to be an upstream issue. We should report the bug upstream where appropriate and close this

**Comment by banesullivan** [comment]
@venkatabhishek, would you be able to help write a bug report for this. I can help you create a minimally working example somewhere if needed.

We can follow the instructions here: https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/

**Comment by venkatabhishek** [comment]
Option 2: https://stackoverflow.com/questions/32037375/geodjango-can-i-use-osmgeoadmin-in-an-inline-in-the-user-admin
