### ISSUE TITLE
Run Cornell's code on Core3D data 

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/ResonantGeoData#4]

**Comment by mleotta** [comment]
here is the code https://kai-46.github.io/VisSat/

**Comment by danlipsa** [comment]
I run the code sucessfully. Shown is an image and the point cloud generated shown in meshlab.

![pointcloud png01](https://user-images.githubusercontent.com/6180727/80851730-8603da00-8bf1-11ea-8859-0f9fb8679cdf.png)
![0005_WV03_15FEB11_135123-P1BS-500497282030_01_P001](https://user-images.githubusercontent.com/6180727/80851804-d713ce00-8bf1-11ea-9fdd-fd9ea0d6f9ae.png)

**Comment by aashish24** [comment]
this is great @danlipsa lets discuss the next step tomorrow.
