### ISSUE TITLE
RGB Raster View

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#421]
We should add a new raster detail view page for previewing the raster in a RGB color mode. I'm thinking the place to start is by specifying this as a new URL:

```
geodata/raster/<int:pk>/rgb/<str:r_params>/<str:g_params>/<str:b_params>
```

This URL would allow the user to specify exactly which ImageEntry's to use from the raster and then which bands within each of those image entries/files to use.

a few different use cases:

- RGB bands all coming from one file (one ImageEntry) in the ImageSet
- RGB bands coming from one band in 3 different files (ImageEntries in the ImageSet)
- then a mix of these two (2 bands from one file and 1 band from another file)

Potential challenge: we do not enforce that a raster's images all be the same resolution or even coverage. Most often they are, but we need to be able to catch the case when they are not and throw an error.

for each of the `str` band params, we could pass the image entry ID `<image_entry_id>` which defaults to the first band in that file, then to specify the band within that file, `<image_entry_id>-<band_index>`

This is just a rough idea of how to do this.

@manthey, can large image support taking three different files and combing bands in them to generate RGB tiles?

**Comment by aashish24** [comment]
Is this for SMART or IH? In general this is a nice feature to have

**Comment by manthey** [comment]
Not currently.  It should be a straightforward addition to make large_image do this.  Currently, you composite bands via something like `style={"bands": [{"band": 1, "palette": ["black", "red"]}, {"band": 2, "palette": ["black", "green"]}]}`.  This would need something like `style={"bands": [{"band": 1, "palette": ["black", "red"]}, {"source": "<some filename>", "band": 1, "palette": ["black", "green"]}]}`.

The other way to do this is with gdal vrt files and use the vrt file as the source.

Go ahead and add a issue to large_image.

**Comment by banesullivan** [comment]
> Is this for SMART or IH? In general this is a nice feature to have

No project specifically -- I believe SMART would benefit from it. I mainly had the idea and wanted to put it on the feature request backlog for later

**Comment by banesullivan** [comment]
This would require upstream features in large_image (ref https://github.com/girder/large_image/issues/680) and some rethinking of our tile endpoints. Since no one is pushing this, I am closing for now

**Comment by manthey** [comment]
For the record, this could be accomplished currently using a vrt file to combine two tile sources.  Otherwise, there is another project which *might* end up allow tiles from multiple files to be composited together.
