### ISSUE TITLE
Set default predicate in web UI search form

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#423]
Most folks understandably forget to set the search predicate which yields confusing search results after inputting a geometry.

We may want to set the default to "contains" as that is what is typically desired.

**Comment by banesullivan** [comment]
We may also want to do this for the Python client

**Comment by aashish24** [comment]
Contains or intersect @banesullivan ?

**Comment by banesullivan** [comment]
The predicates are defined here: https://en.wikipedia.org/wiki/DE-9IM

Jon mentioned it may be useful to but a help icon on the field to point to that Wiki page

Ah good catch, I believe "intersects" is the most permissive. 

- "contains": a contains b: geometry b lies in a, and the interiors intersect.
- "intersects": a intersects b: geometries a and b have at least one point in common.

Here is an example where we are searching for this single raster over SF with search geometry of an ROI within its coverage

| `contains` search (no result) | `intersects` search (desired raster appears) |
|---|---|
| <img width="1406" alt="Screen Shot 2021-06-04 at 12 56 17 PM" src="https://user-images.githubusercontent.com/22067021/120850257-6c3f6f80-c534-11eb-822d-e468fe7a668a.png"> |  <img width="1414" alt="Screen Shot 2021-06-04 at 12 56 32 PM" src="https://user-images.githubusercontent.com/22067021/120850266-6ea1c980-c534-11eb-8fcd-eef0ad72c98d.png"> |
