### ISSUE TITLE
Proper testing for rgd_client

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#443]
We need to implement real tests for the Python client

The tests for this would require running RGD with data prepopulated in the background then executing the client tests

**Comment by banesullivan** [comment]
Rough outline of work:

1. Create new tox env for running the client tests
2. Find a way to launch the example project in the background
3. Write a few basic tests for the client that hit the endpoints

**Comment by venkatabhishek** [comment]
Two things:
- Running the populate commands is quite slow when run in the test environment as fixtures (not sure if this is just my machine). Is it possible to save a smaller sample data set(s) to the database?
- The current approach in the linked PR starts the server as a background process and waits till it is ready. Did we want to consider using mocking? [responses](https://github.com/getsentry/responses) is a nice library for this
