### ISSUE TITLE
Default collection for user uploads

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#474]
We have users that need to be able to upload data to different collections through the Python client.

First, we should set a default collection for each user so that data uploaded by them belong to that collection.

Then, we need to expose functionality in the endpoints/python client that enables users to set the collection for each upload.

**Comment by banesullivan** [comment]
I'm thinking of creating a new model/table called `DefaultUserCollection` that has `ForeignKey`s to each `User` and sets a default `Collection` for each user.

Then I will add a new `user_signed_up` signal handler that creates a `Collection` for the user and populates this table. Something along the lines of:

model:
```py
class DefaultUserCollection(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    collection = models.ForeignKey(Collection, on_delete=models.PROTECT)
```

signal:
```py
@receiver(user_signed_up)
def create_new_user_default_collection(sender, **kwargs):
    user = kwargs.get('user')
    collection = Collection.objects.create()
    permissions = CollectionPermission.objects.create(user=user, role=CollectionPermission.OWNER, collection=collection)
    DefaultUserCollection.create(user=user, collection=collection)
```

**Comment by banesullivan** [comment]
We will also need some sort of mechanism/middleware to capture the user creating any new ChecksumFile and set the collection based on that user's default

**Comment by aashish24** [comment]
In old Girder we used to have public and private by default created for each user. Perhaps we just need one default collection in our case. I am wondering what would be the permission in that case?

**Comment by mcovalt** [comment]
Can each `ChecksumFile` have a `created_by` attribute and the default collection just be a `NULL` for `Collection` and the default collection per user just be the query `ChecksumFile.objects.filter(collection=None, created_by=user)`? It's sometimes tough to coordinate new model creation and dynamic defaults in Django. It can cause some migration headaches.

As far as creating the default `created_by` attribute: this is tough. One option is to use [`django-crum`](https://github.com/ninemoreminutes/django-crum/). This seems weird, but actually works in practice. The more explicit and clear method would be to set this value in every view where `ChecksumFile`s are being made. I would favor the latter if the number of these views are small.

**Comment by banesullivan** [comment]
Ah, that's quite elegant! I'll move forward with that approach. Thanks, @mcovalt!

Note: handle permissions in this case too such that users have access to all files they created
