### ISSUE TITLE
File grouping mechanism

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#519]
Following from https://github.com/ResonantGeoData/RGD-ScrumBoard/issues/38

We need a way to check out multiple files at once in a single directory. The ENVI format is a two file pair and if our files are located remotely via URL then we currently have no way of checking them out in one directory as many of the tools that read them need. (There are other formats similar to this, ENVI is just one example)

This is further complicated by the FUSE utility which requires a `..` suffix on the file paths. This is problematic when we use an external library that expects a specific extension to swap out for another (e.g. `.hdr` for `.raw` in ENVI). The `..` suffix will break any logic in those external libs for swapping the extension.

This is also going to be relevant to the work happening in RD-OASIS as the processing models will need to check out multiple `ChecksumFile`s in a single directory at a time (cc @AlmightyYakob).

----

To proceed with this, I propose that we add an `ancillary_files` field to the `Image` model and adjust the ETL routines to check out/FUSE mount all of those files in one directory when processing. We will extend this logic to other models that already have an `ancillary_files` field.

We will likely have to modify the `simple_httpfs` package to no longer require the suffixed `..` to make this all work. It seems to me that'd we just need to adjust [this section of code](https://github.com/higlass/simple-httpfs/blob/b9195e1fa3888ae256afa7187f488a8aee68b718/simple_httpfs/httpfs.py#L269-L282) and drop support for the `..-wal` and `..-journal` modes. Alternatively, we could open an issue in the `simple-httpfs` repo to see what its devs think about this sort of use case and if there could be support for it (it does not seem terribly active to me though)

**Comment by banesullivan** [comment]
We also need to look into how this could be supported by the Virtual Storage Interface in GDAL and how we can also do this when the files exist in `S3FileField`

**Comment by AlmightyYakob** [comment]
One approach to associating an arbitrary number of files to an image (or any "downstream" model which makes use of `ChecksumFile`), is to create a `ManyToManyField` with `ChecksumFile`, possibly using a [custom intersection table](https://docs.djangoproject.com/en/3.1/topics/db/models/#extra-fields-on-many-to-many-relationships).

The basic implementation might look something like this:

```python
class Image:
	files = models.ManyToManyField(ChecksumFile)
```

If you wanted to store extra data on these relationships, you could do the following:

```python
class Image(models.Model):
	files = models.ManyToManyField(ChecksumFile, through='ImageFile')

class ImageFile(models.Model):
	image = models.ForeignKey(Image, on_delete=models.CASCADE)
    file = models.ForeignKey(ChecksumFile, on_delete=models.CASCADE)
	
	# Extra fields
	raw_file = models.BooleanField(default=False)
```

The advantage of this custom through table is that you can both store additional data on the relationships, as well as enforce constraints on these relationships.

This is a more hands on, model specific approach though. One of the cons of this approach is that this relationship has to be defined and managed for any model downstream. However, it keeps things modular, and doesn't require the upstream models (`ChecksumFile`, etc.) to attempt to solve the problem for any other model which might use it.
