### ISSUE TITLE
Add more base maps

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#522]
Add the base maps from here: https://carto.com/help/building-maps/basemap-list/#carto-vector-basemaps

and this one for google imagery: `https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}`

**Comment by banesullivan** [comment]
GeoJS' `geo.osmLayer.tileSources` contains the named layers. We will add the layers directly to this as well as our drop-down menu.

**Comment by manthey** [comment]
If any of the new tile sources have appropriate licenses, can you add these upstream to geojs as well?

**Comment by banesullivan** [comment]
> If any of the new tile sources have appropriate licenses, can you add these upstream to geojs as well?

Great idea!

@marySalvi, would you give this a go? Should be all JS dev

We currently have a dropdown of all the basemap choices here: https://github.com/ResonantGeoData/ResonantGeoData/blob/c5e968579fda5386d47a090d1a2d611497c407cf/django-rgd/rgd/templates/rgd/_include/empty_viewer.html#L17-L29

Work to complete:

- [ ] Look into the licenses/reuse policies of these different basemaps (make sure there's no restrictive terms)
- [ ] Add any tile sources with clearly permissive licenses upstream to GeoJS' `geo.osmLayer.tileSources`
- [ ] Add any other tile sources with questionable license status at runtime in RGDs' `django-rgd/rgd/templates/rgd/_include/empty_viewer.html` (@manthey, should we be concerned about adding basemaps with either no license or restrictive licenses here)
- [ ] Change the dropdown list in the code snippet above to dynamically fetch the different named tile sources in `geo.osmLayer.tileSources`

**Comment by manthey** [comment]
Generally, we only want to add tile sources to GeoJS if we are *certain* that they are allowed.  For RGD, we might allow less certain tile sources, but it depends on the exposure we have.

I *think* we are okay with the CartoDB maps, since we are using the public API and they list that as free.  They list a limit of "map loads per month".  I can't determine if that is tiles or something else, and is that by IP (e.g., per user) or per parent page (e.g., for RGD)?

For Google, do we think this clause: https://developers.google.com/maps/terms-20180207#10.-license-restrictions. prevents us from using it?  Or, since "the service" is defined as the API and we are using the API, we are okay?  I don't know the answer.

And some further examples:

ArcGIS:
```
  geo.osmLayer.tileSources['arcgis-satellite'] = {
    url: 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.png',
    attribution: '<a href="https://www.esri.com/en-us/search/?q=world%20imagery">Esri World Imagery</a>',
    minLevel: 0,
    maxLevel: 19
  };
```
Would add the ArcGIS ESRI World Imagery.  Use restrictions are listed https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9.  I interpret the license as a *user* needs to have an ArcGIS developer account to use it.  I wouldn't add this to GeoJS, but we could add it to RGD with a warning (probably in the attribution) that you need such an account.

Bing:
```
  geo.osmLayer.tileSources['bing-satellite'] = {
    url: (x, y, z, s) => {
      s = s[modulo(x + y + z, s.length)];
      let tile = '';
      for (; z > 0; z -= 1) {
        let d = (x % 2) + (y % 2) * 2;
        tile = '' + d + tile;
        x = Math.floor(x / 2);
        y = Math.floor(y / 2);
      }
      return `http://ecn.t${s}.tiles.virtualearth.net/tiles/a${tile}.jpeg?g=5000`;
    },
    attribution: '<a href="https://www.microsoft.com/maps/product/terms.html">Microsoft</a> Virtual Earth',
    subdomains: '0123',
    minLevel: 1,
    maxLevel: 19
  };
```
I *think* the TOS for Bing lets us do add this generically, but I'm not sure (we'd have to ask our legal people to be more certain).

**Comment by banesullivan** [comment]
> For Google, do we think this clause: https://developers.google.com/maps/terms-20180207#10.-license-restrictions. prevents us from using it? Or, since "the service" is defined as the API and we are using the API, we are okay? I don't know the answer.

I see some mixed messages in their terms and guidelines:

- Section 10.4e makes it clear that any means of tile access other than through the Google Maps API is forbidden (does this mean we need to be using Google Maps as the tile renderer? or is the tile endpoint a part of the "Maps API" and we're okay?)
    > 10.4e: No use of Content with a non-Google map. You must not use the Content in a Maps API Implementation that contains a non-Google map.
- [This page is a bit more friendly] (https://about.google/brand-resource-center/products-and-services/geo-guidelines/)(linked to by that license). My takeaway from this page is that if we attribute Google _and their data providers_ within the map view, we are okay. Only thing is, I'm not sure how to properly attribute `https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}`

I think we should avoid Google's imagery moving forward.

-----


Re the ArcGIS layers from ESRI, the section:

> You can add this layer to the ArcGIS Online Map Viewer, ArcGIS Desktop, or ArcGIS Pro.

Makes it clear to me that we can't use that imagery because this isn't an ESRI app.

----

Re Bing: Microsoft makes it quite clear we can use their map data in GeoJS (probably considered a "competing platform" to them)

> It should also be noted that Bing Maps data cannot be integrated with competing mapping platforms as noted in the terms of use.

Per https://docs.microsoft.com/en-us/bingmaps/rest-services/directly-accessing-the-bing-maps-tiles

Plus they note:

> It should be noted that the tile URLs for Bing Maps change regularly

Which is probably to prevent people from hard setting those tile URLs in web apps

**Comment by banesullivan** [comment]
ref https://github.com/OpenGeoscience/geojs/pull/1107

**Comment by banesullivan** [comment]
@marySalvi, would you follow up with updating GeoJS:

https://github.com/ResonantGeoData/ResonantGeoData/blob/f796bd2901130532e065daa9aa4937ee834dbd96/django-rgd/rgd/templates/rgd/_base/base.html#L10

to 

```html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/geojs/1.4.2/geo.min.js"></script>
```

when it is released on the CDN: https://cdnjs.com/libraries/geojs to use the new human-readable `name` field from https://github.com/OpenGeoscience/geojs/pull/1107

Then we can mark this as done
