### ISSUE TITLE
3D tiles support and basic CesiumJS viewer

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#590]
Add a new 3D tiles model to the 3D module that leverages the new `FileSet` model and add a basic CesiumJS viewer for it's SSR detail view

Proposal:

- New `Tiles3D` model (better name suggestions?)
    - Point this model to a single `ChecksumFile` - this will be the JSON file and MUST be a part of a `FileSet`. The rest of the data fils in the 3D tiles set must be in that `FileSet`
- Add new `Tiles3DMeta` model that inherits from `SpatialEntry`. Set up an ETL routine on the `Tiles3D` model's save event that will parse the 3D tiles dataset for it's spatial reference and populate the spatial entry

@mcovalt, please review models/relationships here

**Comment by banesullivan** [comment]
Example data here: https://data.kitware.com/#item/6193fcc42fa25629b9d1f9da

**Comment by mcovalt** [comment]
Yeah, those relationships seem good!

**Comment by banesullivan** [comment]
This should be fairly straightforward at this point. I have a "minimal", tokenless CesiumJS viewer here we can adopt for this: https://gist.github.com/banesullivan/e3cc15a3e2e865d5ab8bae6719733752

To view 3D tiles data with it, it *should* just be something like the following code but I can't get this working. I opened a support discussion here: https://community.cesium.com/t/cesium3dtileset-not-loading-tileset-json-from-any-url-and-silently-failing-with-bad-urls/16287

```js
var tileset = new Cesium.Cesium3DTileset({
  url: 'http://0.0.0.0:8089/1.0/TilesetWithRequestVolume/tileset.json',
});
viewer.scene.primitives.add(tileset);
viewer.zoomTo(tileset);

tileset.readyPromise.then(function () {
  console.log('Ready!')
  viewer.zoomTo(
    tileset,
    new Cesium.HeadingPitchRange(
      0.0,
      -0.5,
      tileset.boundingSphere.radius / 4.0
    )
  );
});
```
