### ISSUE TITLE
Remove `RGD_GLOBAL_READ_ACCESS`?

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#612]
`RGD_GLOBAL_READ_ACCESS` has a lot of overhead and complicates our permissions filtering significantly. I propose removing it outright and requiring `ChecksumFiles` (or `FileSet`) to have a `Collection` field and for users to be explicitly given permissions. 

For deployments that want all users to have access to all data, they can add in hooks to add users to all collections on sign up and to add all users to any collection when it is created - this would be far simpler to handle downstream.

cc @mcovalt 

additionally, `RGD_GLOBAL_READ_ACCESS` isn't fully working right now

**Comment by banesullivan** [comment]
Either this or we literally interpret `RGD_GLOBAL_READ_ACCESS` to mean that ALL users have access to ALL data and move this up in the `filter_perm()` logic so that it improves query performance

**Comment by mcovalt** [comment]
Right now the business logic regarding `RGD_GLOBAL_READ_ACCESS` is [fairly concise](https://github.com/ResonantGeoData/ResonantGeoData/blob/main/django-rgd/rgd/permissions.py#L148-L154) and I believe causes negligible impact on perfromance. I do understand that perhaps this business logic _is wrong_. If so, we definitely need to address that. I vote that we at least initially formulate why the business logic is wrong in terms of SQL, then determine if the added complexity is too much.
