### ISSUE TITLE
Base Python client improvements

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#629]
- [x] new method to download any ChecksumFile (@mvandenburgh)
- [x] new search method to utilize ChecksumFile filtering from #570 (@AlmightyYakob)
- [x] client methods for adding and modifying Collections (@mvandenburgh)
- [ ] Basically make sure all API methods from the core app are exposed in the core plugin (@AlmightyYakob)

@AlmightyYakob and @mvandenburgh, do you both want to look into splitting up this work?

**Comment by AlmightyYakob** [comment]
Sure, @mvandenburgh and I can coordinate on this.

**Comment by banesullivan** [comment]
@mvandenburgh and @AlmightyYakob, I need the `create_file_from_url` method on the Python client to act like a "get or create" method to prevent duplicate data.

Please note the new unique constraint on URLs in #633 

I would like this client method to first check if a file exists for the given URL and collection. If it exists, return that. If it doesn't exist, post a new one.

Similarly, I need this implemented for the `post_stac` method on the watch client in https://github.com/ResonantGeoData/RD-WATCH/pull/42

I need this functionality ASAP - can we work to get a small PR just for this first and then finish the rest of this work?

**Comment by AlmightyYakob** [comment]
> I would like this client method to first check if a file exists for the given URL and collection. If it exists, return that. If it doesn't exist, post a new one.

Just an FYI, I think this would require a new endpoint for retrieving a checksum file from a url.

**Comment by banesullivan** [comment]
Specifically, this would be done through a filter on the existing Viewset. no new endpoint

**Comment by banesullivan** [comment]
URL would be a text field on this endpoint:
![Screen Shot 2021-12-10 at 10 29 15 AM](https://user-images.githubusercontent.com/22067021/145616423-26599984-1044-4f2c-aa8e-86f0835a17eb.png)

**Comment by banesullivan** [comment]
One more thing to figure out:

https://github.com/ResonantGeoData/ResonantGeoData/pull/633/files#r767013110

What's the needed configuration? Let's add that to the tests and document somewhere
