### ISSUE TITLE
Create raster data model that can store multispectral data

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/ResonantGeoData#64]

**Comment by banesullivan** [comment]
#56 implements a basic solution - if these data are in a GDAL supported format, then we can ingest these data types into the database. Each band of the multi/hyper-spectral dataset will be stored as bands under a single raster.

One caveat is that if the multispectral data's bands are saved to individual files like Landsat 8, then we would have several different `RasterEntry`s for the single raster.

Next step: create an ingestion routine that allows a user to upload a collection of raster files, check if they belong to the same raster space -> if so, create a single `RasterEntry` where each file is stored under a single bad
