### ISSUE TITLE
Regression: STAC endpoint for RasterMeta missing

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#641]
This client method is not working:

```py
stac = client.imagery.get_raster(result, stac=True)
```

This is because the underlying STAC endpoint changed.

@mcovalt, is it possible to convert a Raster to STAC without using a Collection ID?

**Comment by mcovalt** [comment]
> is it possible to convert a Raster to STAC without using a Collection ID?

Not anymore; a STAC Item must belong to a collection per the STAC API spec. Luckily, though, this condition also holds for our data model; the collection is implicitly in the collection with ID `default` if `ChecksumFile.collection == None`.
