### ISSUE TITLE
Clean up Python client and test

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#643]
There are a few remnants of STAC support in the Python client which were moved to WATCH - these need to be removed

Additionally, many of the python client methods are failing -- entirely due to the fact that we changed many of the views/endpoints and forgot to update these.

To mitigate these issues, we need to make sure we have a test for every method of the Python client that calls on an endpoint.

**Comment by banesullivan** [comment]
@AlmightyYakob, do you have a status update? I know you and @mvandenburgh worked on a few PRs/issues related to this and I'm wondering what is left.

**Comment by AlmightyYakob** [comment]
I'm not sure, #648 and #649 seem to be in this vein but I don't know if they fully address this issue.
