### ISSUE TITLE
Create RESTApi to search raster data 

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/ResonantGeoData#65]
* By geospatial bounds
* By type of image (multispectral / hyperspectral)
* By temporal bounds

**Comment by aashish24** [comment]
we can provide / expose more options in the REST API - I would think that most of it could be key value pairs.

**Comment by manthey** [comment]
Girder 3 Geospatial Plugin
-----------------------------

The Girder 3 geospatial plugin provides the following query fields:

- latitude
- longitude
- radius
- relation (one of Mongo's geospatial query operators https://docs.mongodb.com/manual/reference/operator/query-geospatial/)
- bbox
- geometry (geojson geometry for the query in wkt format)
- geojson

where one of 4 possible searches is done: latitude/longitude/radius, bbox/relation, geometry/relation, geojson/relation.  Perhaps oddly, the `bbox`, `geometry`, and `geojson` parameters are treated identically (that is, each is the appropriate json representation for whatever Mongo expects for the `relation` operator).  

The latitude/longitude/radius search is performed as `{$geoWithin: {$centerSphere: [[longitude, latitude], radius/radius_of_earth]}}`

As such, the REST search is a thin veneer over Mongo's queries.  There is no direct support for faceted search with key-value information.  There is no support for time-based queries.

ResonantGeoData Search
----------------------------

We want faceted search.  I think we want full facet control (e.g., the sensor is one of a list, the sensor altitude is between two values, etc.).  This could be one way to implement time-based searches.

We want to support the various available functions: ST_Equals, ST_Disjoint, ST_Intersects, ST_Touches, ST_Crosses, ST_Within, ST_Contains, ST_Overlaps, ST_Relate, plus ST_Distance with optional upper and lower bounds.  We want inputs to be either WKT, GeoJSON, or simple values like latitude/longitude/altitude.

If we want to support complex operations, we will need some way to construct such queries, which means either a custom query language or a more transparent way to expose SQL.  For instance, I could see ultimately wanting to know what regions have n or more datasets that cover them in some time.

For video datasets, I could see wanting to query if any frame intersects with some location or if all of the video so intersects.

I think we want to support a **general** search endpoint that can do complex searches and have **simple** search endpoints for specific use cases.  For instance:

- GET `geometa/search` could take a JSON search parameter which could be a list of:
  {'geometry': <wkt or geojson>, 'function': <one of the geospatial functions>, 'value': <the value to match>, 'operator': <defaults to '=', but would support <, <=, >, >=, !=, 'srid': <value>}
  or 
  {'key': <facet name>, 'value': <the value to match>, 'operator': <this could also contain regex, etc.>}

  But here we are creating our own query language, and it would be better to use an existing one that is feature rich enough to provide what we want.  If we allow nesting, then we can support and/or joining of the terms.  The main code is to convert this query to sql.

- GET `geometa/near_point` would take `latitude`, `longitude`, `altitude`, `radius`, and optionally `time`, `timespan`.

Thoughts?

**Comment by manthey** [comment]
As a further thought, do we want to expose other functions?  For instance, would it every be useful to find data base on its area or perimeter?

**Comment by manthey** [comment]
In the Girder database assetstore plugin, we generically exposed non-mutating database functions.  The functionality of this borders on exposing SQL in general (which could be done as an optional where clause).  This has the virtue that a client can construct sophisticated queries, but the drawback that you need to ensure that whatever queries are used are non-mutating.  There are some database functions that mutate database state that could be allowed (calls to random, for instance, which change the state of the random number generator, but would permit an arbitrary sampling of data).

**Comment by aashish24** [comment]
> As a further thought, do we want to expose other functions? For instance, would it every be useful to find data base on its area or perimeter?

May be I think it will be hard to cover all of the use cases so our full faceted search API needs to be flexible so that additional parameters can be added in the future. I would n't add these in the first pass. thoughts @banesullivan @brianhelba

**Comment by aashish24** [comment]
> ST_Equals, ST_Disjoint, ST_Intersects, ST_Touches, ST_Crosses, ST_Within, ST_Contains, ST_Overlaps, ST_Relate, plus ST_Distance with optional upper and lower bounds. 

This sounds about right.
> We want inputs to be either WKT, GeoJSON, or simple values like latitude/longitude/altitude.

For the inputs WKT or GeoJSON would be a good start - I would just pick one for now and later support others but yeah this sounds like a good idea. 

> If we want to support complex operations, we will need some way to construct such queries, which means either a custom query language or a more transparent way to expose SQL. For instance, I could see ultimately wanting to know what regions have n or more datasets that cover them in some time.

My inclination is towards a transparent way to expose SQL - perhaps we can look into if something already exists along these lines. A custom query language seems does not seem best as it will be hard to maintain.

**Comment by aashish24** [comment]
@manthey @banesullivan @brianhelba perhaps we can start with something small (a handful set of parameters and end points with options to expand) is probably be my wish list. @manthey if that sounds good, it would be great if we can list out those small set here on the github.

**Comment by banesullivan** [comment]
I think this can be marked done. As more endpoints are desired, we can open new issues for them like #152
