### ISSUE TITLE
Converting to ESPG from the RasterMeta CRS fails

### ISSUE THREAD

**Issue by mcovalt** [ResonantGeoData/ResonantGeoData#657]
The [projection extension in the STAC API fails](https://github.com/ResonantGeoData/ResonantGeoData/blob/66b0b3ed43e8ce74c9f01aad11aa4fb05340cb8d/django-rgd-imagery/rgd_imagery/stac/serializers/item/__init__.py#L72-L77) when given a CRS of `'+init=epsg:None +type=crs'`.

**Comment by banesullivan** [comment]
Actually... where were you seeing this error? can we reproduce this for a specific raster? We need to figure out where `crs` is being not being set correctly

**Comment by banesullivan** [comment]
Leaving open to gether a bit more context

**Comment by mcovalt** [comment]
These are only erroring from the `drop1` collections.

**Comment by banesullivan** [comment]
Aha, I think someone mentioned this morning that the bounds, etc. of the drop1 STAC items are messed up. #638 should suffice. Though we may want to have the STAC ingest in RD-WATCH handle null crs to make sure the value is desired rather than what is assumed in #638
