### ISSUE TITLE
Create a ETL workflow to ingest raster data 

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/ResonantGeoData#66]

**Comment by banesullivan** [comment]
A first pass of this has been implemented in #56 

The current ETL routine for raster data is implemented as: 

1. User uploads a GDAL supported raster file (GeoTIFF, `.jp2`, etc. - [any format accepted by GDAL](https://gdal.org/drivers/raster/index.html)) into a `RasterFile` DB entry.
    - this `RasterFile` points to the file on the local file system
    - On the post save event, a routine to load that data is called... (next step) If fails, a failure message is saved to the `RasterFile` entry
2. `RasterEntryReader` performs the ETL steps
    - `RasterEntryReader` is instantiated and passed the ID of the `RasterFile` DB entry
    - the `RasterFile`'s file is passed to [`GDALRaster`](https://docs.djangoproject.com/en/3.0/ref/contrib/gis/gdal/#gdalraster) which loads the raster using GDAL into a new raster entry in the database, effectively copying the data and storing it in the PostGIS database
    - We use `rasterio` to open/load some additional metadata from the raster file into our `RasterEntry` model.
    - The `RasterEntry` model is saved and owns the `GDALRaster` entry

After the `RasterEntry` model is added to the DB, we no longer need to keep the `RasterFile` as the data has been copied and verified into the database. We now have the data stored in the database under a single standard which we could build up the rest of the API around.

**Comment by banesullivan** [comment]
Note: we can expand step 1 (the ingestion) to accept other known formats not supported by GDAL quite easily

**Comment by aashish24** [comment]
Thanks for all the details @banesullivan this is very helpful. See my question below:

when does the RasterEntryReader gets invoked? Is it on post save event? Could you list out your view on pros and cons on saving the data in the database as that would be very helpful when we discuss it this week.
