### ISSUE TITLE
Can data be ingested on public RGD instance?

### ISSUE THREAD

**Issue by russelldj** [ResonantGeoData/ResonantGeoData#723]
Hi all,

Very exciting work! I was curious if there's a way to demo ingesting your own data on the public instance? I didn't see any options or documentation. Sorry if this is an oversight on my part.

David

**Comment by banesullivan** [comment]
There are ways, yes - though our focus has not been on users directly uploading their own data but rather on ingesting large catalogs of open data like Landsat and Sentinel for users to access, search, and visualize.

@russelldj, let's catch up face-to-face and we can go over what RGD and the ecosystem it's built on can provide. I'll send a calendar invite
