### ISSUE TITLE
Add readers for known hyperspectral remote sensing data formats not supported by GDAL

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/ResonantGeoData#81]

**Comment by aashish24** [comment]
Related to #64

**Comment by banesullivan** [comment]
As far as the models are concerned, there is no difference between Hyper- vs. Multi-spectral data. Hyper just has more bands than Multi.

Requires #69 

The difference here could lie in the file formats - so, once we've collected data per #69 we can move forward with this task. Likely, the format of the data for #69 will be supported by GDAL and we will not have to change anything. In the event that they are not supported by GDAL, we can use this issue to keep track of the progress for implementing a file reader for those formats.

As new formats become known that are not supported by GDAL out of the box, we can open new issues for those formats individually.
