### ISSUE TITLE
use base name of uploaded files by default in GeoData app

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#83]
if no name is specified for a raster file or geometry archive, use the base name of the file for the name.

from https://github.com/ResonantGeoData/ResonantGeoData/pull/56#issuecomment-649766048

**Comment by banesullivan** [comment]
@manthey, should we implement this by overriding the `save()` method on the model or in a view form?

**Comment by manthey** [comment]
I think it would be better in the `save` method.
