### ISSUE TITLE
Include geodata endpoints in swagger

### ISSUE THREAD

**Issue by manthey** [ResonantGeoData/ResonantGeoData#87]

**Comment by manthey** [comment]
We might want to generate serializers based on models rather than explicitly define each of them.  Any code that is need both by core and geodata should be moved to a common module (rgs/utility.py, for instance).

**Comment by banesullivan** [comment]
@manthey, is there a status on this? From my perspective the endpoints seem listed in swagger but it seems there is additional work for this in #106?

**Comment by manthey** [comment]
There is an open PR that @mattrix27 started.  I think it still needed some work, but I haven't checked on it. 

Specifically, we have endpoints for search and some other actions, but this was to add at least some CRUD endpoints for models.

**Comment by banesullivan** [comment]
> ... but this was to add at least some CRUD endpoints for models.

Ah, I see. Do you want to look into finishing that PR or should I put it on my todo list?
