### ISSUE TITLE
Redesign geodata models to support non-spatial data

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#98]
Per team discussion, we need to support non-spatial imagery as well.

I will brainstorm a new model hierarchy and post it here, then sync up with David about the implementation. I already have a few ideas about how we can make this work in a general fashion while keeping the `SpatialEntry` concept that informed our initial model design.

**Comment by banesullivan** [comment]
I have an idea of how to do this with the introduction of a new `ImageEntry` model, a bit of renaming and refactoring of other models. The premise is that our model hierarchy stemming from `ModifiableEntry` will be all non-spatial in nature, supporting `ImageEntry`s and `Annotation`s on those images. Then we intermix the `SpatialEntry` model via dual inheritance for things like `RasterEntry` and `GeometryEntry`. That way a `RasterEntry` is simply an expansion of `ImageEntry` with spatial features. `GeometryEntry` will remain a `SpatialEntry` as I cannot think of a use case where it wouldn't have a spatial reference.

This will give us a lot of flexibility when needing to introduce new models to our database, spatial or not.

I have a UML diagram sketched out (by hand), but it isn't pretty. I will get started on implementing this in a draft PR and then generate the UML diagram automatically for discussion and refinement.

**Comment by aashish24** [comment]
@banesullivan what you describe makes sense to me. I also like the naming convention, thanks for thinking through it and making changes as necessary.

**Comment by banesullivan** [comment]
I have been testing out the reworking on the `non-spatial` branch. The current model inheritance is as follows:

![geodata](https://user-images.githubusercontent.com/22067021/87588525-d26b9b80-c6b1-11ea-864d-873c240fcdc6.png)


------

These changes abstract the concept of a raster a bit further, implementing a new `ImageryEntry` that will be generated anytime an `ImageFile` is uploaded. These entries do not have a spatial reference. The `ImageryEntry` is a foreign key to `BandMeta` for cataloging band info.

Then, the `RasterEntry` model has a `ManyToMany` relationship owning `ImageryEntry`s. Why `ManyToMany`? because Django doesn't support `OneToMany` and would require the use of a `ForeignKey` on `ImageryEntry` to do that. Since we are supporting non-spatial data, I didn't think it makes sense to have all `ImageryEntry`s have a field pointing to a `RasterEntry` when that could be empty in a lot of cases. Also, this enables us to resolve #77 as this way we can upload many different `ImageryEntry`s for Landsat use cases then have a form to create a `RasterEntry` of many `ImageryEntry`s.

This will require some reworking of the ETL routines but nothing too crazy. Now when a user uploads a raster, it will generate an `ImageryEntry` and they will have to create a `RasterEntry` pointing to all the `ImageryEntry`s they want via the admin interface.

This still has one complication that I am not sure how to deal with yet: annotations. Annotations will have a `ForeignKey` of `ImageryEntry`. But the annotations themselves are typically Polygon shapes... how do we support `PolygonField`s in a non-spatial reference frame (i.e. image coordinates). Should we just change that to a JSON field that stores the GEOJSON for the Polygon?

**Comment by banesullivan** [comment]
Also, with these changes, the `Dataset` model is now a container for all `ModifiableEntry`s. This means we can group together any datasets/files (spatial or non-spatial) for specific projects.

**Comment by manthey** [comment]
I think we will want to facilitate the common case of one image file in a raster entry.  I could see that this would be done when creating a new ImageFile -- if we had an optional form field (not reflected in the model) of a RasterEntry.  On upload, we always will create a corresponding ImageEntry to match the ImageFile.  If the extra RasterEntry field is blank, we would create a new RasterEntry for the single ImageEntry.  If the RasterEntry field is populated, we would add the new ImageEntry to that existing RasterEntry.

**Comment by manthey** [comment]
In the medical world, we also have grouped images (multiple image files with the same sample imaged with different light sources, for instance).  I could see having multiple images files that should be grouped together but don't have geospatial data.  Do we want the models to reflect this?  That is, should there be an `ImageSet` model that has the `ManyToMany` reference to `ImageEntry` and then `RasterEntry` would have a `ForeignKey` reference to `ImageSet`?

If we decided to have an `ImageSet` model, the `ImageEntry` could have a `ForeignKey` to it, and then the `ImageSet` would not have a `ManyToMany` field for images.

**Comment by banesullivan** [comment]
Aha, that's a great approach. I'll work to implement a new `ImageSet` model as this will resolve issues with those relationships and still let us handle the common use case in #77

**Comment by manthey** [comment]
For annotations on non-spatial images, I think we can just use an SRID of 0 in the database and have the convention that the scale of the units is pixels.

**Comment by banesullivan** [comment]
> I think we can just use an SRID of 0 in the database

Is it possible to mix the SRIDs of what is stored in the database? I was under the impression that all entries must be under one SRID? Especially since we set the SRID in the model field, e.g.

https://github.com/ResonantGeoData/ResonantGeoData/blob/39c54fa14836b6769d5d91188ddee0a57f9057f0/geodata/models/common.py#L42

**Comment by banesullivan** [comment]
Okay, I've added a new `ImageSet` model. Should it have any fields? Currently, `ImageEntry` has a foreign key to it and `RasterEntry` has a `OneToOneField` relationship with it

![geodata](https://user-images.githubusercontent.com/22067021/88187560-ab0e5480-cc04-11ea-993f-d2f920b3363e.png)

**Comment by manthey** [comment]
I think that is sufficient.  Since it is a `ModifableEntry`, we may (eventually) want code so that when an `ImageEntry` adds or removes a reference to the `ImageSet`, the modified information is updated.  Perhaps such information can be extracted from the admin log, though.

**Comment by manthey** [comment]
> Is it possible to mix the SRIDs of what is stored in the database? I was under the impression that all entries must be under one SRID? Especially since we set the SRID in the model field, e.g.

I just fiddled a bit with PostGIS.  Specifically, it lets you store coordinates that should make no sense in the specified SRID (for instance, `ST_SetSRID(ST_MakePoint(5000, 5000), 4326)`).  If, in queries, you don't do any transforms, you get the coordinates exactly as set.  Internally, you can set the SRID on any column.  If the column has an SRID of 0, it allows a geometry of any SRID; otherwise, the geometry has to be converted to the column's SRID before storage or PostGIS throws an error like `ERROR:  Geometry SRID (0) does not match column SRID (4326)`.

I think this means that if we store pixel coordinates, provided we know that we've got pixel coordinates, it will work in our current database.  We may want a flag on the annotation to mark that the stored coordinates are pixel coordinates.  Otherwise, making a query for any data with annotations at a specific longitude and latitude will also return data with annotations near that location in pixel space (and vice versa).
